import Head from 'next/head'
import Image from 'next/image'
import ItemList from "../components/home/itemlist"


export default function Home() {

  return (
    <>
      <Head>
        <title>Ecomm Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ItemList />
      </main>
    </>
  )
}
